# Generated by Django 3.1.4 on 2020-12-14 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('none', 'Select Department'), ('comp', 'Computer'), ('it', 'Information Technology'), ('mech', 'Mechanical'), ('civil', 'Civil'), ('etc', 'E and TC'), ('elc', 'Electrical')], default='none', max_length=10)),
                ('classis', models.CharField(choices=[('none', 'Select Class'), ('fe', 'First Year'), ('se', 'Second Year'), ('te', 'Third Year'), ('be', 'Final Year')], default='none', max_length=5)),
                ('roll_no', models.IntegerField()),
                ('add_info', models.CharField(blank=True, max_length=1000)),
                ('resume', models.FileField(upload_to='')),
                ('studid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
