# Generated by Django 3.1.4 on 2020-12-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnpPortal', '0002_auto_20201214_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='companyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('tenth_marks', models.PositiveIntegerField()),
                ('twelth_marks', models.PositiveIntegerField()),
                ('degree_marks', models.PositiveIntegerField()),
                ('live_back', models.PositiveIntegerField()),
                ('selected_stud', models.PositiveIntegerField()),
            ],
        ),
    ]
