# Generated by Django 3.1.4 on 2020-12-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnpPortal', '0003_companydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='degree_marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='live_back',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='tenth_marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='twelth_marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='roll_no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
