# Generated by Django 3.1.4 on 2020-12-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnpPortal', '0006_auto_20201214_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='selected_stud',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
