# Generated by Django 3.1.4 on 2020-12-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnpPortal', '0010_auto_20201214_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='selected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('studid', models.PositiveIntegerField()),
                ('s_username', models.CharField(max_length=100)),
            ],
        ),
    ]
