# Generated by Django 3.1.4 on 2020-12-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnpPortal', '0011_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='resume',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
